theme: jekyll-theme-slate
title: Fiish-YU
email: excentrique@163.com
description: > # this means to ignore newlines until "baseurl:"
  Enjoy the life. Happy all the time.

url: "https://fiiish-yu.github.io"
social_sites:
  github:  Fiiish-YU